{{- if .Values.mysql.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-only-from-web
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: web
    ports:
    - protocol: TCP
      port: 3306
  policyTypes:
  - Ingress
{{- end }}
