{{- if .Values.monitor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher
  labels:
    app: pod-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-watcher-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher-binding
subjects:
- kind: ServiceAccount
  name: pod-watcher
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-watcher-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
